### ISSUE TITLE
Jamepad 2.0.12.1 is not yet released as I change to 2.1.0 without having to build gdx-controllers?

### ISSUE THREAD

**Issue by LucasFebatis** [libgdx/gdx-controllers#1]
In build.gradle the desktop module has a

// FIXME change it after first official libgdx-Jamepad release

how could I do this fix to use in my project?

**Comment by MrStahlfelge** [comment]
It can't get fixed before the first official libgdx Jamepad release is done.
This will be done before the first stable release of gdx-controllers.

For the time being, the desktop implementation relies on MrStahlfelge/Jamepad.

**Comment by MrStahlfelge** [comment]
libgdx/Jamepad is released now, and this, too.
