### ISSUE TITLE
gdx-controllers 2.2.2 requires unnecessary Android permissions due to low target SDK

### ISSUE THREAD

**Issue by 00-Evan** [libgdx/gdx-controllers#22]
Apologies, as I was the one who pushed for the release of 2.2.2, and there seems to be an issue with it.

When attempting to release an update to my app which now uses controllers 2.2.2, I was given a warning by Google Play about new permission usage.

After digging into the merged manifest I found three new permissions: READ_PHONE_STATE, READ_EXTERNAL_STORAGE, and WRITE_EXTERNAL_STORAGE. All of these have the reason: "Implied from the shattered-pixel-dungeon.android main manifest (this file), line 1; reason: com.badlogicgames.gdx.controllers has a targetSdkVersion < 4"

When comparing the manifests of the gdx-controllers-android AAR, 2.2.2 has:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.badlogicgames.gdx.controllers" >

    <uses-sdk android:minSdkVersion="1" />

    <application />

</manifest>
```

Tested this locally and It seems this was caused by the AGP plugin update, for some reason the gradle properties 'minSdk' and 'targetSdk' aren't sticking, but changing the variable names to anything else (e.g. "androidMinSdk and androidTargetSdk') works properly.

For the moment this can be circumvented by adding these lines to my app's manifest. Controllers 2.2.2 works just fine with the permissions removed:

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove"/>
```

**Comment by MrStahlfelge** [comment]
Thanks - new snapshot is being published

**Comment by 00-Evan** [comment]
The snapshot version is still 2.2.2-SNAPSHOT, but after deleting my cache and re-downloading I can confirm that the correct manifest is now being generated:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.badlogicgames.gdx.controllers" >

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="29" />

    <application />

</manifest>
```

**Comment by 00-Evan** [comment]
I see 2.2.3-SNAPSHOT now. It also has the correct manifest values
