### ISSUE TITLE
IntArray object spam in JamepadControllerMonitor

### ISSUE THREAD

**Issue by IljaGnezdilov** [libgdx/gdx-controllers#24]
Method JamepadControllerMonitor#update() has line
        `IntArray disconnectedControllers = new IntArray(indexToController.size);`

This IntArray is created every time (200-300 numbers per second). I want to suggest use some private IntArray variable for same reason.

**Comment by MrStahlfelge** [comment]
Sure, go for it.

**Comment by IljaGnezdilov** [comment]
Ok.

Can I branch from master and create pull request?

**Comment by MrStahlfelge** [comment]
Yes, the usual workflow fork -> new branch -> commit -> push -> open PR

**Comment by IljaGnezdilov** [comment]
I think that I must have some permissions.

Push failed
Remote: Permission to libgdx/gdx-controllers.git denied to IljaGnezdilov.
unable to access 'https://github.com/libgdx/gdx-controllers.git/': The requested URL returned error: 403

**Comment by MrStahlfelge** [comment]
https://github.com/MarcDiethelm/contributing/blob/master/README.md

**Comment by IljaGnezdilov** [comment]
Done.
