### ISSUE TITLE
Potential non reporting of events on iOS

### ISSUE THREAD

**Issue by Berstanio** [libgdx/gdx-controllers#27]
So, I can't tell whether this bug really exists in the mobiVM backend, but I guess it does. I have encountered the bug with a fork that uses a 1 to 1 translates MOE backend.
#### So whats the problem:
https://github.com/libgdx/gdx-controllers/blob/88092dd3772fa083932574ba94cad0ae776b1c44/gdx-controllers-ios/src/com/badlogic/gdx/controllers/IosController.java#L112
The valueChangedHandler is called from objc side and expects either a object of type "GCControllerButtonInput" or "GCControllerDirectionPad".
But at this point it isn't (probably) guarenteed that "bro" (iirc this was how the java-native bridge was called in mobiVM) knows that the binding classes exist, since their static init block, that register the classes, haven't needed to run yet.
This probably leads to bro falling back to the super class when creating the binding object, so "GCControllerElement". And this object will fall through all the "instanceof" checks silently.
At least this is what happens with MOE and NatJ (MOE's bro). But I think the same will happen also with mobiVM and bro.

#### How to fix
A simple fix is just forcing the static init block to run at the start.

#### Why doesn't that happen always?
Because probably in nearly all cases "getButton" or "getAxis" is called, which would run the static init block of the classes and would register them.
https://github.com/libgdx/gdx-controllers/blob/88092dd3772fa083932574ba94cad0ae776b1c44/gdx-controllers-ios/src/com/badlogic/gdx/controllers/IosController.java#L286-L287

If I'm able to fix my setup I can say whether this bug really exists. Or anyone else can test this. Anyhow, I thought it is better to report it as not reporting it.

**Comment by MrStahlfelge** [comment]
I can confidently say that everything is working as expected on robovm/mobivm, so I am closing this issue. Feel free to reopen if your test say otherwise.
