### ISSUE TITLE
Android: getCurrent is always null

### ISSUE THREAD

**Issue by KanedaFr** [libgdx/gdx-controllers#28]
On Android, while Controllers.getControllers() is not an empty list, Controllers.getCurrent() return null
if i use Controllers.getControllers().get(0), no problem

I suspect listeners.add(new ManageCurrentControllerListener()); to be the culprit.
Event is never fired because Controllers is initialized too late, after input related initiliaze events.

It tried to initialize Controllers right after Gdx (so after AndroidApplication.initialize() ) but it's not working either.
I can't register this event sooner, on Application create for exemple, since Gdx isn't ready yet....

**Comment by MrStahlfelge** [comment]
getCurrent is null before the first button is pressed or another change event happens
