### ISSUE TITLE
Incompatible with RoboVM 2.3.19

### ISSUE THREAD

**Issue by klianc09** [libgdx/gdx-controllers#34]
Gdx-Controllers is currently incompatible with RoboVM 2.3.19. Using Gdx-Controllers 2.2.3 with RoboVM 2.3.19 will yield the following exception: 

> java.lang.NoSuchMethodError: org.robovm.apple.gamecontroller.GCController$Notifications.observeDidConnect(Lorg/robovm/objc/block/VoidBlock1;)Lorg/robovm/apple/foundation/NSObjectProtocol;
 at com.badlogic.gdx.controllers.IosControllerManager.initializeControllerArray(IosControllerManager.java:86)

Due to the following changes in RoboVM: https://github.com/MobiVM/robovm/pull/683

MobiVM/RoboVM dependency needs to be upgraded to 2.3.19 to resolve this.

**Comment by klianc09** [comment]
May I request that a release for this is made so I don't have to depend on my locally built snapshot?

**Comment by MrStahlfelge** [comment]
Hi, you can already use the public snapshot. You can even set a fixed version or only use the snapshot dependency for the ios subproject.
I usually wait around 14 days before doing a release to give everyone the chance to test, and this time we are broken on mac os so we should solve that problem first.

**Comment by klianc09** [comment]
That's fine! Just learned that I can depend on a specific commit with jitpack, that will do for me. Sorry for the bother!
