### ISSUE TITLE
Can't run desktop module

### ISSUE THREAD

**Issue by HeinousGames** [libgdx/gdx-controllers#4]
Versions:
gdxVersion = '1.9.11'
gdxControllersVersion = '2.0.0' or '2.0.1-SNAPSHOT'

Trying to build the desktop module results in an error of "Could not resolve com.badlogicgames.jamepad:jamepad:2.0.12.1."
Even though I know the dependency is included in the desktop dependency, I tried adding it as a separate dependency and it still would not be found. Maybe the repo location is down or the source was moved?

**Comment by MrStahlfelge** [comment]
It is available on Maven Central: https://search.maven.org/artifact/com.badlogicgames.jamepad/jamepad/2.0.12.1/jar
Maybe check again?

**Comment by HeinousGames** [comment]
So I did check that it was being hosted on maven before reaching out, and I bundled the jar in a libs folder for desktop as well, and I still would get the error about badlogicgames.jamepad.jamepad not resolving. Setting the target and source compatibility in the gradle file resolved the issue, although I wish the error message made it more clear as to how to resolve it.

**Comment by MrStahlfelge** [comment]
Good to hear issue is resolved. In my case, the error message was hidden by the IDE and command line gradle was giving a better error message.
