### ISSUE TITLE
SDL should not require a mapping db entry for a generic joystick/gamepad device "behind" an adaptor

### ISSUE THREAD

**Issue by bomb2777** [libgdx/gdx-controllers#45]
Hi, I raise this issue here as a follow up of https://github.com/mdqinc/SDL_GameControllerDB/pull/783.

My gdxControllersVersion is '2.2.2'.
I have some old adaptor with an old gamepad connected:
![image](https://github.com/user-attachments/assets/7ed34a6c-f7c3-4680-9fc3-3be712b4e9c6)

This device is not recognized by `Controllers.getControllers()`. 
To get it recognized, i did the folowing:
1. create a mapping string with Steam's Big Picture Mode
2. add the string to `gamecontrollerdb.txt`
3. replace the original `gamecontrollerdb.txt` with the modified one (by unpacking jar, replace file, re-pack jar)
4. my game is recognizing the device now

When Steam can recognize my device (without `gamecontrollerdb.txt` modification), shouldn't gdx-controllers do the same?

**Comment by MrStahlfelge** [comment]
> When Steam can recognize my device (without gamecontrollerdb.txt modification), shouldn't gdx-controllers do the same?

The features of the lib are not set in stone, but are defined by Jamepad in this case. The controller db is just a convenience for SDL and you can configure every controller mapping in pure code. If you are willing to, feel free to submit a PR to Jamepad to support controllers not listed in db.

**Comment by bomb2777** [comment]
thx for explanation, maybe I do this, maybe I am happy with the solution I described above .... don't know yet :grinning:
