### ISSUE TITLE
Keyboard as an optional Controller

### ISSUE THREAD

**Issue by msx80** [libgdx/gdx-controllers#46]
Hi there, it would be nice if there was an option to have an optional controller bound to the keyboard. It would be reported as just another controller, obviously with minimal features (no vibro, no analog). I know that libgdx already has support for keyboard input but it's a bit ugly to have different mechanics for the two inputs. Ideally one could implement a two player games that can be played with a keyboard and a gamepad (as well as with two gamepads) using the same code, just handling two Controller objects.

Another benefit is that button mapping would be standardized to the same keys for any game.

Or maybe something like this already exists ?

Thanks

**Comment by MrStahlfelge** [comment]
It does not exist, I made something like that in my own game (lightblocks) by abstracting the input method. But it is more fitting into the gdx-controllerutils project as it already provides a mapping feature. Feel free to add it there.
